In [25]:
import torch
x=torch.arange(12)
print(x)
print(x.shape)
print(x.size())
# 此处因为是向量，所以shape与size相同
# 获取张量元素的个数
print(x.numel())
# 改变张量的形状而不改变元素数量与元素值，可以用reshape
print(x.reshape(3,4))
# 我们可以只传入高度或宽度，在pyTorch中，另一个可以自动被计算出来
print(x.reshape(4,-1))
# 全0
print(torch.zeros((2,2,2)))
# 全1
print(torch.ones((2,2,3)))
# 随机初始化，高斯分布随机采样
print(torch.randn(3,4))
# 提供列表来转化为tensor
print(torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[ 0.2806,  0.1453, -0.4248,  1.3734],
        [ 0.4305, -0.8265,  0.7748, -0.1360],
        [-0.5326,  1.0085,  1.4954, -1.9555]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


In [26]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
# 常见的标准量运算符都可以升级为按元素运算
print(x+y)
print(x-y)
print(x/y)
print(x*y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 2.,  4.,  8., 16.])


In [27]:
# 按元素运算可以应用更多的运算，比如求幂运算
print(torch.exp(x))

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [29]:
x=torch.arange(12).reshape(3,4)
y=torch.tensor([[2,1,4,3],[5,6,4,8],[8,9,6,3]])
print(torch.cat((x,y),dim=0))
print(torch.cat((x,y),dim=1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 5,  6,  4,  8],
        [ 8,  9,  6,  3]])
tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  5,  6,  4,  8],
        [ 8,  9, 10, 11,  8,  9,  6,  3]])


In [31]:
x.sum()

tensor(66)

In [35]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
c = torch.arange(3).reshape(3, 1)
print(a.shape)
print(b)
print(c.shape)
a+b

torch.Size([3, 1])
tensor([[0, 1]])
torch.Size([3, 1])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [41]:
print(x)
print(x[-1])
print(x[1:3])
print(x[1,1])
print(x[1,1:3])
print(x[2,])



tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 8,  9, 10, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor(5)
tensor([5, 6])
tensor([ 8,  9, 10, 11])


In [48]:
x=torch.arange(24).reshape(2,3,4)
x[1:3]=12
print(x)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 12, 12, 12],
         [12, 12, 12, 12],
         [12, 12, 12, 12]]])


In [49]:
z = torch.zeros_like(x)
print(f"idz:{id(z)}")
z[:] = x+z
print(f"idz:{id(z)}")


idz:2220999240824
idz:2220999240824


In [68]:
x=torch.arange(12).reshape(3,4)
A=x.numpy()
b=torch.from_numpy(A)
print(A)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [69]:
A += 500
print("A",A)
print("b",b)
print("x",x)

A [[500 501 502 503]
 [504 505 506 507]
 [508 509 510 511]]
b tensor([[500, 501, 502, 503],
        [504, 505, 506, 507],
        [508, 509, 510, 511]])
x tensor([[500, 501, 502, 503],
        [504, 505, 506, 507],
        [508, 509, 510, 511]])


In [78]:
a = torch.tensor([3.5])
print(a.shape)
b = torch.tensor(3.5)
print(b.shape)
print(type(b))

torch.Size([1])
torch.Size([])
<class 'torch.Tensor'>
