In [1]:
import os
os.makedirs(os.path.join("..","data"),exist_ok=True)
data_file=os.path.join("..","data","house_tiny.csv")
with open(data_file,"w") as f:
    f.write("NUmRooms,Alley,Price\n")
    f.write("NA,Pave,125700\n")
    f.write("2,NA,106000\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")

In [2]:
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NUmRooms Alley   Price
0       NaN  Pave  125700
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [3]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NUmRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


d:\anaconda\envs\class_face\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [8]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NUmRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1
   NUmRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [20]:
import torch
print(inputs)
print(outputs)
print(inputs.values)
x,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
#print(x)
#print(y)

   NUmRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1
0    125700
1    106000
2    178100
3    140000
Name: Price, dtype: int64
[[3. 1. 0.]
 [2. 0. 1.]
 [4. 0. 1.]
 [3. 0. 1.]]


In [26]:
a=2
X = torch.arange(24).reshape(2, 3, 4)
print(X)
print(a + X)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])


In [42]:
a=torch.arange(24).reshape(4,6)
print(a)
sum=a.sum(axis=[0,1])
print(sum)
print(sum.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
tensor(276)
torch.Size([])


In [44]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A.shape)
sum_A = A.sum(axis=1, keepdims=True)
print(sum_A.shape)
print(sum_A)

torch.Size([5, 4])
torch.Size([5, 1])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


In [47]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A2 = A.sum(axis=1)
print(sum_A.shape)
print(sum_A2.shape)
print(A/sum_A)

torch.Size([5, 1])
torch.Size([5])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


In [49]:
B = torch.ones(4, 3)
A = torch.ones(5, 4)
C = torch.mm(A, B)
print(C)


tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [56]:
a = torch.tensor([24])
print(a)
len(a)

tensor([24])


1